-- P1 expand: introduce normalized master/reference structures without dropping
-- legacy columns. V110 backfills data; V120 installs final P1 constraints.

CREATE SCHEMA IF NOT EXISTS migration;

CREATE TABLE admin_users (
  id         VARCHAR(32) NOT NULL,
  name       VARCHAR(100) NOT NULL,
  email      VARCHAR(254) NOT NULL,
  role       VARCHAR(32) NOT NULL,
  active     BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT pk_admin_users PRIMARY KEY (id)
);

CREATE TABLE customer_shipping_addresses (
  id             BIGINT GENERATED BY DEFAULT AS IDENTITY,
  customer_id    VARCHAR(32) NOT NULL,
  recipient_name VARCHAR(100) NOT NULL,
  postal_code    VARCHAR(10) NOT NULL,
  city           VARCHAR(50) NOT NULL,
  district       VARCHAR(50) NOT NULL,
  address_line   VARCHAR(300) NOT NULL,
  phone          VARCHAR(32) NOT NULL,
  is_default     BOOLEAN NOT NULL DEFAULT FALSE,
  created_at     TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at     TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT pk_customer_shipping_addresses PRIMARY KEY (id)
);

CREATE TABLE preference_options (
  id         BIGINT GENERATED BY DEFAULT AS IDENTITY,
  type       VARCHAR(32) NOT NULL,
  code       VARCHAR(64) NOT NULL,
  label      VARCHAR(100) NOT NULL,
  sort_order INTEGER NOT NULL DEFAULT 0,
  active     BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT pk_preference_options PRIMARY KEY (id)
);

CREATE TABLE customer_preferences (
  customer_id  VARCHAR(32) NOT NULL,
  preference_id BIGINT NOT NULL,
  CONSTRAINT pk_customer_preferences PRIMARY KEY (customer_id, preference_id)
);

CREATE TABLE customer_tags (
  id         BIGINT GENERATED BY DEFAULT AS IDENTITY,
  name       VARCHAR(100) NOT NULL,
  color      VARCHAR(32) NOT NULL,
  sort_order INTEGER NOT NULL DEFAULT 0,
  active     BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT pk_customer_tags PRIMARY KEY (id)
);

CREATE TABLE customer_tag_assignments (
  customer_id VARCHAR(32) NOT NULL,
  tag_id      BIGINT NOT NULL,
  CONSTRAINT pk_customer_tag_assignments PRIMARY KEY (customer_id, tag_id)
);

CREATE TABLE product_categories (
  id         BIGINT GENERATED BY DEFAULT AS IDENTITY,
  code       VARCHAR(64) NOT NULL,
  name       VARCHAR(100) NOT NULL,
  sort_order INTEGER NOT NULL DEFAULT 0,
  active     BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT pk_product_categories PRIMARY KEY (id)
);

CREATE TABLE inventory_locations (
  id               VARCHAR(32) NOT NULL,
  code             VARCHAR(32) NOT NULL,
  inventory_domain VARCHAR(16) NOT NULL,
  type             VARCHAR(32) NOT NULL,
  branch_id        VARCHAR(32),
  name             VARCHAR(120) NOT NULL,
  active           BOOLEAN NOT NULL DEFAULT TRUE,
  created_at       TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at       TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT pk_inventory_locations PRIMARY KEY (id)
);

ALTER TABLE customers
  ADD COLUMN avatar_url TEXT,
  ADD COLUMN active BOOLEAN NOT NULL DEFAULT TRUE;

ALTER TABLE brands
  ADD COLUMN active BOOLEAN NOT NULL DEFAULT TRUE,
  ADD COLUMN created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  ADD COLUMN updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW();

ALTER TABLE campgrounds
  ADD COLUMN active BOOLEAN NOT NULL DEFAULT TRUE,
  ADD COLUMN created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  ADD COLUMN updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW();

ALTER TABLE campground_zones
  ADD COLUMN active BOOLEAN NOT NULL DEFAULT TRUE,
  ADD COLUMN created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  ADD COLUMN updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW();

ALTER TABLE branches
  ADD COLUMN code VARCHAR(32),
  ADD COLUMN business_hours VARCHAR(200),
  ADD COLUMN image_url TEXT,
  ADD COLUMN active BOOLEAN NOT NULL DEFAULT TRUE,
  ADD COLUMN created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  ADD COLUMN updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW();

CREATE TABLE migration.p1_location_aliases (
  alias       VARCHAR(200) NOT NULL,
  location_id VARCHAR(32) NOT NULL,
  source      VARCHAR(100) NOT NULL,
  CONSTRAINT pk_p1_location_aliases PRIMARY KEY (alias)
);

CREATE TABLE migration.p1_location_quarantine (
  source_table       VARCHAR(100) NOT NULL,
  source_row_id      VARCHAR(64) NOT NULL,
  field_name         VARCHAR(64) NOT NULL,
  raw_value          VARCHAR(200) NOT NULL,
  reason             TEXT NOT NULL,
  disposition_status VARCHAR(32) NOT NULL DEFAULT 'PENDING_REVIEW',
  created_at         TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT pk_p1_location_quarantine
    PRIMARY KEY (source_table, source_row_id, field_name, raw_value)
);
