-- P2 expand: introduce normalized catalog, campground tag and store stock
-- structures. V210 backfills data; V220 installs final constraints and removes
-- the P2 legacy JSONB/cache columns after guarded reconciliation.

CREATE TABLE equipment_items (
  id             VARCHAR(32) NOT NULL,
  category_id    BIGINT NOT NULL,
  brand_id       VARCHAR(32) NOT NULL,
  name           VARCHAR(200) NOT NULL,
  main_image_url TEXT,
  description    TEXT,
  active         BOOLEAN NOT NULL DEFAULT TRUE,
  created_at     TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at     TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT pk_equipment_items PRIMARY KEY (id)
);

CREATE TABLE equipment_images (
  item_id    VARCHAR(32) NOT NULL,
  sort_order INTEGER NOT NULL,
  url        TEXT NOT NULL,
  alt_text   VARCHAR(200),
  CONSTRAINT pk_equipment_images PRIMARY KEY (item_id, sort_order)
);

CREATE TABLE equipment_tags (
  item_id VARCHAR(32) NOT NULL,
  tag     VARCHAR(100) NOT NULL,
  CONSTRAINT pk_equipment_tags PRIMARY KEY (item_id, tag)
);

CREATE TABLE equipment_interest_tags (
  item_id VARCHAR(32) NOT NULL,
  tag     VARCHAR(100) NOT NULL,
  CONSTRAINT pk_equipment_interest_tags PRIMARY KEY (item_id, tag)
);

CREATE TABLE equipment_specifications (
  item_id  VARCHAR(32) NOT NULL,
  spec_key VARCHAR(100) NOT NULL,
  value    TEXT NOT NULL,
  CONSTRAINT pk_equipment_specifications PRIMARY KEY (item_id, spec_key)
);

CREATE TABLE environment_tags (
  id         BIGINT GENERATED BY DEFAULT AS IDENTITY,
  code       VARCHAR(64) NOT NULL,
  label      VARCHAR(100) NOT NULL,
  sort_order INTEGER NOT NULL DEFAULT 0,
  active     BOOLEAN NOT NULL DEFAULT TRUE,
  CONSTRAINT pk_environment_tags PRIMARY KEY (id)
);

CREATE TABLE facility_tags (
  id         BIGINT GENERATED BY DEFAULT AS IDENTITY,
  code       VARCHAR(64) NOT NULL,
  label      VARCHAR(100) NOT NULL,
  sort_order INTEGER NOT NULL DEFAULT 0,
  active     BOOLEAN NOT NULL DEFAULT TRUE,
  CONSTRAINT pk_facility_tags PRIMARY KEY (id)
);

CREATE TABLE campground_environment_tags (
  campground_id VARCHAR(32) NOT NULL,
  tag_id        BIGINT NOT NULL,
  CONSTRAINT pk_campground_environment_tags PRIMARY KEY (campground_id, tag_id)
);

CREATE TABLE campground_facility_tags (
  campground_id VARCHAR(32) NOT NULL,
  tag_id        BIGINT NOT NULL,
  CONSTRAINT pk_campground_facility_tags PRIMARY KEY (campground_id, tag_id)
);

CREATE TABLE inventory_stocks (
  location_id      VARCHAR(32) NOT NULL,
  variant_id       VARCHAR(64) NOT NULL,
  on_hand_quantity INTEGER NOT NULL DEFAULT 0,
  updated_at       TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT pk_inventory_stocks PRIMARY KEY (location_id, variant_id)
);

-- Immutable migration evidence retained outside the business schema so P2
-- compatibility queries can compare the contracted model with the frozen
-- source payload after legacy JSONB columns are removed.
CREATE TABLE migration.p2_product_source (
  product_id VARCHAR(32) NOT NULL,
  payload    JSONB NOT NULL,
  CONSTRAINT pk_p2_product_source PRIMARY KEY (product_id)
);

CREATE TABLE migration.p2_campground_tag_source (
  campground_id   VARCHAR(32) NOT NULL,
  environment_tags JSONB NOT NULL,
  facility_tags    JSONB NOT NULL,
  CONSTRAINT pk_p2_campground_tag_source PRIMARY KEY (campground_id)
);

ALTER TABLE products
  ADD COLUMN item_id VARCHAR(32);

ALTER TABLE product_variants
  ADD COLUMN specification VARCHAR(200),
  ADD COLUMN status VARCHAR(16) NOT NULL DEFAULT 'active',
  ADD COLUMN created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  ADD COLUMN updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW();
