-- P4 expand: create the normalized transaction targets alongside the legacy
-- tables. V410 performs the deterministic fixture backfill; V420 validates and
-- switches the public names.

CREATE SCHEMA IF NOT EXISTS migration;

CREATE TABLE orders_p4 (
  id VARCHAR(32) NOT NULL,
  customer_id VARCHAR(32) NOT NULL,
  buyer_name_snapshot VARCHAR(100) NOT NULL,
  buyer_email_snapshot VARCHAR(254) NOT NULL,
  recipient_name_snapshot VARCHAR(100) NOT NULL,
  shipping_address_snapshot TEXT NOT NULL,
  shipping_phone_snapshot VARCHAR(32) NOT NULL,
  subtotal NUMERIC(14, 2) NOT NULL,
  shipping_fee NUMERIC(12, 2) NOT NULL,
  discount NUMERIC(14, 2) NOT NULL,
  total NUMERIC(14, 2) NOT NULL,
  payment_method VARCHAR(24) NOT NULL,
  payment_status VARCHAR(24) NOT NULL,
  refund_status VARCHAR(24) NOT NULL DEFAULT 'none',
  status VARCHAR(24) NOT NULL,
  placed_at TIMESTAMPTZ NOT NULL,
  paid_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE order_items_p4 (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  order_id VARCHAR(32) NOT NULL,
  product_id VARCHAR(32) NOT NULL,
  variant_id VARCHAR(64) NOT NULL,
  sku_snapshot VARCHAR(64) NOT NULL,
  product_name_snapshot VARCHAR(200) NOT NULL,
  specification_snapshot VARCHAR(200) NOT NULL,
  brand_name_snapshot VARCHAR(120) NOT NULL,
  image_url_snapshot TEXT,
  unit_price_snapshot NUMERIC(12, 2) NOT NULL,
  quantity INTEGER NOT NULL
);

CREATE TABLE order_status_history_p4 (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  order_id VARCHAR(32) NOT NULL,
  status VARCHAR(24) NOT NULL,
  occurred_at TIMESTAMPTZ NOT NULL,
  actor_id VARCHAR(32),
  note TEXT
);

CREATE TABLE coupons_p4 (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  code VARCHAR(64) NOT NULL,
  name VARCHAR(120) NOT NULL,
  discount_type VARCHAR(16) NOT NULL,
  discount_value NUMERIC(12, 2) NOT NULL,
  minimum_amount NUMERIC(12, 2) NOT NULL DEFAULT 0,
  issue_quantity INTEGER NOT NULL,
  valid_from TIMESTAMPTZ NOT NULL,
  valid_until TIMESTAMPTZ NOT NULL,
  status VARCHAR(16) NOT NULL,
  category VARCHAR(64),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE order_coupons_p4 (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  order_id VARCHAR(32) NOT NULL,
  coupon_id BIGINT,
  code_snapshot VARCHAR(64) NOT NULL,
  discount_type_snapshot VARCHAR(16) NOT NULL,
  discount_value_snapshot NUMERIC(12, 2) NOT NULL,
  amount NUMERIC(12, 2) NOT NULL,
  applied_at TIMESTAMPTZ NOT NULL
);

CREATE TABLE coupon_usage_adjustments_p4 (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  order_coupon_id BIGINT NOT NULL,
  adjustment_type VARCHAR(16) NOT NULL,
  quantity_delta SMALLINT NOT NULL,
  idempotency_key VARCHAR(128) NOT NULL,
  reason TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE calendar_dates_p4 (
  calendar_date DATE NOT NULL,
  is_holiday BOOLEAN NOT NULL,
  holiday_name VARCHAR(120),
  source_version VARCHAR(64) NOT NULL,
  effective_at TIMESTAMPTZ NOT NULL,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE bookings_p4 (
  id VARCHAR(32) NOT NULL,
  customer_id VARCHAR(32) NOT NULL,
  campground_id VARCHAR(32) NOT NULL,
  campground_name_snapshot VARCHAR(150) NOT NULL,
  region_snapshot VARCHAR(100) NOT NULL,
  check_in DATE NOT NULL,
  check_out DATE NOT NULL,
  guest_count INTEGER NOT NULL,
  weekday_count INTEGER NOT NULL,
  holiday_count INTEGER NOT NULL,
  zone_total NUMERIC(14, 2) NOT NULL,
  rental_total NUMERIC(14, 2) NOT NULL,
  applied_discount NUMERIC(14, 2) NOT NULL,
  final_amount NUMERIC(14, 2) NOT NULL,
  status VARCHAR(24) NOT NULL,
  created_at TIMESTAMPTZ NOT NULL,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE booking_selected_zones_p4 (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  booking_id VARCHAR(32) NOT NULL,
  zone_id VARCHAR(32) NOT NULL,
  zone_type_snapshot VARCHAR(64) NOT NULL,
  price_weekday_snapshot NUMERIC(12, 2) NOT NULL,
  price_holiday_snapshot NUMERIC(12, 2) NOT NULL,
  quantity INTEGER NOT NULL
);

CREATE TABLE booking_selected_rentals_p4 (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  booking_id VARCHAR(32) NOT NULL,
  rental_listing_id VARCHAR(64) NOT NULL,
  rental_sku_variant_id VARCHAR(64) NOT NULL,
  sku_snapshot VARCHAR(64) NOT NULL,
  name_snapshot VARCHAR(200) NOT NULL,
  specification_snapshot VARCHAR(200) NOT NULL,
  price_weekday_snapshot NUMERIC(12, 2) NOT NULL,
  price_holiday_snapshot NUMERIC(12, 2) NOT NULL,
  discount_snapshot NUMERIC(12, 2) NOT NULL,
  quantity INTEGER NOT NULL
);

CREATE TABLE booking_status_history_p4 (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  booking_id VARCHAR(32) NOT NULL,
  status VARCHAR(24) NOT NULL,
  occurred_at TIMESTAMPTZ NOT NULL,
  actor_id VARCHAR(32),
  note TEXT
);

CREATE TABLE product_stock_reservations_p4 (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  order_item_id BIGINT NOT NULL,
  variant_id VARCHAR(64) NOT NULL,
  location_id VARCHAR(32) NOT NULL,
  quantity INTEGER NOT NULL,
  status VARCHAR(16) NOT NULL DEFAULT 'active',
  idempotency_key VARCHAR(128) NOT NULL,
  reserved_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  expires_at TIMESTAMPTZ,
  released_at TIMESTAMPTZ,
  fulfilled_at TIMESTAMPTZ
);

CREATE TABLE rental_stock_reservations_p4 (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  booking_selected_rental_id BIGINT NOT NULL,
  rental_sku_variant_id VARCHAR(64) NOT NULL,
  location_id VARCHAR(32) NOT NULL,
  check_in DATE NOT NULL,
  check_out DATE NOT NULL,
  quantity INTEGER NOT NULL,
  status VARCHAR(16) NOT NULL DEFAULT 'active',
  idempotency_key VARCHAR(128) NOT NULL,
  reserved_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  released_at TIMESTAMPTZ,
  fulfilled_at TIMESTAMPTZ
);

CREATE TABLE migration.p4_order_source (
  id VARCHAR(32) PRIMARY KEY,
  payload JSONB NOT NULL
);

CREATE TABLE migration.p4_coupon_source (
  code VARCHAR(64) PRIMARY KEY,
  payload JSONB NOT NULL
);

CREATE TABLE migration.p4_booking_source (
  id VARCHAR(32) PRIMARY KEY,
  payload JSONB NOT NULL
);

CREATE TABLE migration.p4_action_map (
  domain VARCHAR(16) NOT NULL,
  legacy_action TEXT NOT NULL,
  status VARCHAR(24) NOT NULL,
  note_pattern VARCHAR(64),
  PRIMARY KEY (domain, legacy_action)
);

CREATE TABLE migration.p4_booking_day_count_resolution (
  booking_id VARCHAR(32) PRIMARY KEY,
  source_weekday_count INTEGER NOT NULL,
  source_holiday_count INTEGER NOT NULL,
  resolved_weekday_count INTEGER,
  resolved_holiday_count INTEGER,
  resolution_method VARCHAR(64) NOT NULL,
  disposition_status VARCHAR(24) NOT NULL,
  reason TEXT NOT NULL
);

CREATE TABLE migration.p4_rental_price_reconciliation (
  booking_id VARCHAR(32) NOT NULL,
  rental_ordinal INTEGER NOT NULL,
  rental_listing_id VARCHAR(64) NOT NULL,
  official_weekday_count INTEGER NOT NULL,
  official_holiday_count INTEGER NOT NULL,
  current_weekday_price NUMERIC(12, 2) NOT NULL,
  current_holiday_price NUMERIC(12, 2) NOT NULL,
  current_discount NUMERIC(12, 2) NOT NULL,
  chosen_weekday_price NUMERIC(12, 2),
  chosen_holiday_price NUMERIC(12, 2),
  chosen_discount NUMERIC(12, 2),
  stored_subtotal NUMERIC(14, 2) NOT NULL,
  calculated_subtotal NUMERIC(14, 2) NOT NULL,
  disposition_status VARCHAR(24) NOT NULL,
  reason TEXT NOT NULL,
  PRIMARY KEY (booking_id, rental_ordinal)
);

CREATE TABLE migration.p4_zone_price_reconciliation (
  booking_id VARCHAR(32) NOT NULL,
  zone_ordinal INTEGER NOT NULL,
  zone_id VARCHAR(32) NOT NULL,
  official_weekday_count INTEGER NOT NULL,
  official_holiday_count INTEGER NOT NULL,
  current_weekday_price NUMERIC(12, 2) NOT NULL,
  current_holiday_price NUMERIC(12, 2) NOT NULL,
  chosen_weekday_price NUMERIC(12, 2),
  chosen_holiday_price NUMERIC(12, 2),
  stored_subtotal NUMERIC(14, 2) NOT NULL,
  calculated_subtotal NUMERIC(14, 2) NOT NULL,
  disposition_status VARCHAR(24) NOT NULL,
  reason TEXT NOT NULL,
  PRIMARY KEY (booking_id, zone_ordinal)
);

CREATE TABLE migration.p4_snapshot_fallbacks (
  domain VARCHAR(16) NOT NULL,
  source_id VARCHAR(32) NOT NULL,
  field_name VARCHAR(64) NOT NULL,
  fallback_source VARCHAR(128) NOT NULL,
  reason TEXT NOT NULL,
  PRIMARY KEY (domain, source_id, field_name)
);

CREATE TABLE migration.p4_rental_reservation_quarantine (
  booking_id VARCHAR(32) NOT NULL,
  rental_ordinal INTEGER NOT NULL,
  rental_listing_id VARCHAR(64) NOT NULL,
  rental_sku_variant_id VARCHAR(64) NOT NULL,
  location_id VARCHAR(32) NOT NULL,
  check_in DATE NOT NULL,
  check_out DATE NOT NULL,
  quantity INTEGER NOT NULL,
  reason_code VARCHAR(32) NOT NULL,
  reason TEXT NOT NULL,
  disposition_status VARCHAR(24) NOT NULL,
  PRIMARY KEY (booking_id, rental_ordinal)
);
