-- P5 expand: introduce normalized policy, availability, minimum-stock and
-- single-domain movement structures beside the legacy P0 tables. V510 loads
-- the adjudicated fixtures; V520 validates and switches the public names.

CREATE SCHEMA IF NOT EXISTS migration;

CREATE TABLE booking_policies_p5 (
  id SMALLINT NOT NULL,
  booking_window_days INTEGER NOT NULL,
  advance_days INTEGER NOT NULL,
  max_nights INTEGER NOT NULL,
  timezone VARCHAR(64) NOT NULL DEFAULT 'Asia/Taipei',
  date_boundary_hour SMALLINT NOT NULL DEFAULT 0,
  low_availability_threshold INTEGER NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE booking_policy_occupying_statuses (
  policy_id SMALLINT NOT NULL,
  status VARCHAR(24) NOT NULL
);

CREATE TABLE booking_policy_availability_statuses (
  policy_id SMALLINT NOT NULL,
  status VARCHAR(24) NOT NULL
);

CREATE TABLE zone_blocks_p5 (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  legacy_block_id VARCHAR(32) NOT NULL,
  campground_id VARCHAR(32) NOT NULL,
  zone_id VARCHAR(32) NOT NULL,
  start_date DATE NOT NULL,
  end_date DATE NOT NULL,
  blocked_quantity INTEGER NOT NULL,
  reason TEXT NOT NULL,
  created_by VARCHAR(32) NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE campground_closures_p5 (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  legacy_closure_id VARCHAR(32) NOT NULL,
  campground_id VARCHAR(32) NOT NULL,
  closure_type VARCHAR(16) NOT NULL,
  start_date DATE,
  end_date DATE,
  weekday SMALLINT,
  effective_from DATE,
  effective_to DATE,
  reason TEXT NOT NULL,
  created_by VARCHAR(32) NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE product_variant_min_stocks (
  variant_id VARCHAR(64) NOT NULL,
  location_id VARCHAR(32) NOT NULL,
  minimum_quantity INTEGER NOT NULL,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE rental_sku_variant_min_stocks (
  rental_sku_variant_id VARCHAR(64) NOT NULL,
  location_id VARCHAR(32) NOT NULL,
  minimum_quantity INTEGER NOT NULL,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE inventory_movements (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  movement_no VARCHAR(64) NOT NULL,
  legacy_movement_id VARCHAR(64),
  inventory_domain VARCHAR(16) NOT NULL,
  movement_type VARCHAR(32) NOT NULL,
  status VARCHAR(16) NOT NULL,
  source_location_id VARCHAR(32),
  destination_location_id VARCHAR(32),
  employee_id VARCHAR(32) NOT NULL,
  reason TEXT NOT NULL,
  occurred_at TIMESTAMPTZ NOT NULL,
  posted_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE store_inventory_movement_items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  movement_id BIGINT NOT NULL,
  inventory_domain VARCHAR(16) NOT NULL DEFAULT 'store',
  variant_id VARCHAR(64) NOT NULL,
  sku_snapshot VARCHAR(64) NOT NULL,
  item_name_snapshot VARCHAR(200) NOT NULL,
  quantity INTEGER NOT NULL
);

CREATE TABLE rental_inventory_movement_items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  movement_id BIGINT NOT NULL,
  inventory_domain VARCHAR(16) NOT NULL DEFAULT 'rental',
  rental_sku_variant_id VARCHAR(64) NOT NULL,
  sku_snapshot VARCHAR(64) NOT NULL,
  item_name_snapshot VARCHAR(200) NOT NULL,
  quantity INTEGER NOT NULL
);

CREATE TABLE inventory_conversions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  source_movement_id BIGINT NOT NULL,
  destination_movement_id BIGINT NOT NULL,
  source_variant_id VARCHAR(64) NOT NULL,
  destination_rental_variant_id VARCHAR(64) NOT NULL,
  source_location_id VARCHAR(32) NOT NULL,
  destination_location_id VARCHAR(32) NOT NULL,
  quantity INTEGER NOT NULL,
  idempotency_key VARCHAR(128) NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE movement_migration_map (
  legacy_movement_id VARCHAR(64) NOT NULL,
  legacy_item_ordinal INTEGER NOT NULL,
  store_item_id BIGINT,
  rental_item_id BIGINT,
  conversion_id BIGINT,
  quarantine_reason TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Fixed domain columns let V520 replace the P4 single-column location FKs with
-- composite domain FKs without changing the reservation API payload.
ALTER TABLE product_stock_reservations
  ADD COLUMN inventory_domain VARCHAR(16) NOT NULL DEFAULT 'store';
ALTER TABLE rental_stock_reservations
  ADD COLUMN inventory_domain VARCHAR(16) NOT NULL DEFAULT 'rental';

-- Frozen migration inputs and adjudication evidence. These tables remain in
-- the migration schema and are not application write targets.
CREATE TABLE migration.p5_policy_source (
  id SMALLINT PRIMARY KEY,
  payload JSONB NOT NULL
);

CREATE TABLE migration.p5_zone_block_source (
  legacy_id VARCHAR(32) PRIMARY KEY,
  payload JSONB NOT NULL
);

CREATE TABLE migration.p5_closure_source (
  legacy_id VARCHAR(32) PRIMARY KEY,
  payload JSONB NOT NULL
);

CREATE TABLE migration.p5_min_stock_source (
  inventory_domain VARCHAR(16) NOT NULL,
  target_id VARCHAR(32) NOT NULL,
  location_id VARCHAR(32) NOT NULL,
  minimum_quantity INTEGER NOT NULL,
  PRIMARY KEY (inventory_domain, target_id, location_id)
);

CREATE TABLE migration.p5_movement_source (
  legacy_movement_id VARCHAR(64) PRIMARY KEY,
  payload JSONB NOT NULL
);

CREATE TABLE migration.p5_location_resolution (
  legacy_label VARCHAR(128) PRIMARY KEY,
  location_id VARCHAR(32),
  inventory_domain VARCHAR(16),
  legacy_code VARCHAR(32),
  resolution_method VARCHAR(64) NOT NULL,
  evidence TEXT NOT NULL,
  disposition_status VARCHAR(32) NOT NULL
);

CREATE TABLE migration.p5_variant_resolution (
  legacy_movement_id VARCHAR(64) NOT NULL,
  legacy_item_ordinal INTEGER NOT NULL,
  product_id VARCHAR(32) NOT NULL,
  product_name_snapshot VARCHAR(200) NOT NULL,
  product_variant_id VARCHAR(64) NOT NULL,
  rental_sku_variant_id VARCHAR(64),
  resolution_method VARCHAR(64) NOT NULL,
  disposition_status VARCHAR(64) NOT NULL,
  PRIMARY KEY (legacy_movement_id, legacy_item_ordinal)
);

COMMENT ON TABLE migration.p5_location_resolution IS
  'P5 deterministic location adjudication; old camp labels are proven by historical code/order and rental-stock vectors.';
COMMENT ON TABLE migration.p5_variant_resolution IS
  'P5 exact product-name-with-variant resolution; similarity and first-variant fallbacks are forbidden.';
