-- P6 expand: create normalized review/article targets beside the P0 legacy
-- tables. V610 performs deterministic source backfill and V620 reconciles,
-- constrains and switches the public names.

CREATE SCHEMA IF NOT EXISTS migration;

CREATE TABLE reviews_p6 (
  id VARCHAR(32) NOT NULL,
  order_item_id BIGINT NOT NULL,
  rating SMALLINT NOT NULL,
  comment TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE review_photos (
  review_id VARCHAR(32) NOT NULL,
  sort_order INTEGER NOT NULL,
  url TEXT NOT NULL
);

CREATE TABLE legacy_reviews (
  id VARCHAR(32) NOT NULL,
  customer_id VARCHAR(32) NOT NULL,
  product_id VARCHAR(32) NOT NULL,
  variant_id VARCHAR(64) NOT NULL,
  sku_snapshot VARCHAR(64),
  buyer_name_snapshot VARCHAR(100),
  buyer_avatar_snapshot TEXT,
  product_name_snapshot VARCHAR(200),
  rating SMALLINT NOT NULL,
  comment TEXT,
  created_at TIMESTAMPTZ NOT NULL,
  legacy_reason TEXT NOT NULL
);

CREATE TABLE legacy_review_photos (
  legacy_review_id VARCHAR(32) NOT NULL,
  sort_order INTEGER NOT NULL,
  url TEXT NOT NULL
);

CREATE TABLE articles_p6 (
  id VARCHAR(32) NOT NULL,
  title VARCHAR(250) NOT NULL,
  category VARCHAR(64) NOT NULL,
  author VARCHAR(120) NOT NULL,
  author_avatar_url TEXT,
  published_at TIMESTAMPTZ,
  summary TEXT NOT NULL,
  cover_image_url TEXT,
  reading_minutes INTEGER NOT NULL,
  featured BOOLEAN NOT NULL DEFAULT FALSE,
  status VARCHAR(16) NOT NULL DEFAULT 'draft',
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE article_tags (
  article_id VARCHAR(32) NOT NULL,
  tag VARCHAR(100) NOT NULL
);

CREATE TABLE article_content_blocks_p6 (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  article_id VARCHAR(32) NOT NULL,
  sort_order INTEGER NOT NULL,
  block_type VARCHAR(16) NOT NULL,
  text_content TEXT,
  product_id VARCHAR(32)
);

CREATE TABLE article_related_products_p6 (
  article_id VARCHAR(32) NOT NULL,
  product_id VARCHAR(32) NOT NULL,
  sort_order INTEGER NOT NULL
);

-- Frozen source payloads and the explicit 1/37 disposition are migration
-- evidence, never application write targets.
CREATE TABLE migration.p6_review_source (
  id VARCHAR(32) PRIMARY KEY,
  payload JSONB NOT NULL
);

CREATE TABLE migration.p6_article_source (
  id VARCHAR(32) PRIMARY KEY,
  payload JSONB NOT NULL
);

CREATE TABLE migration.p6_review_resolution (
  review_id VARCHAR(32) PRIMARY KEY,
  disposition VARCHAR(16) NOT NULL,
  order_item_id BIGINT,
  resolution_method VARCHAR(64) NOT NULL,
  legacy_reason TEXT
);

COMMENT ON TABLE migration.p6_review_resolution IS
  'P6 exact review disposition: REV031 formal; 37 rows without orderId remain read-only legacy evidence.';
