-- Change coupon capacity from redemption-time competition to claim-time
-- allocation. Backend/API behavior will be added separately.

CREATE TYPE public.coupon_claim_status AS ENUM (
  'claimed',
  'consumed',
  'revoked',
  'expired'
);

ALTER TABLE public.coupons
  DROP CONSTRAINT ck_coupons_consumed_quantity;

ALTER TABLE public.coupons
  RENAME COLUMN consumed_quantity TO claimed_quantity;

ALTER TABLE public.coupons
  ADD CONSTRAINT ck_coupons_claimed_quantity CHECK (
    claimed_quantity >= 0
    AND claimed_quantity <= issue_quantity
  );

COMMENT ON COLUMN public.coupons.claimed_quantity IS
  'Atomic claim allocation counter; cannot exceed issue_quantity.';

CREATE TABLE public.coupon_claims (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  coupon_id BIGINT NOT NULL,
  customer_id VARCHAR(32) NOT NULL,
  status public.coupon_claim_status NOT NULL DEFAULT 'claimed',
  claimed_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  consumed_at TIMESTAMPTZ,
  revoked_at TIMESTAMPTZ,
  CONSTRAINT pk_coupon_claims PRIMARY KEY (id),
  CONSTRAINT fk_coupon_claims_coupon_id
    FOREIGN KEY (coupon_id) REFERENCES public.coupons(id)
    ON UPDATE CASCADE ON DELETE RESTRICT,
  CONSTRAINT fk_coupon_claims_customer_id
    FOREIGN KEY (customer_id) REFERENCES public.customers(id)
    ON UPDATE CASCADE ON DELETE RESTRICT,
  CONSTRAINT uq_coupon_claims_coupon_customer
    UNIQUE (coupon_id, customer_id),
  CONSTRAINT ck_coupon_claims_timestamps CHECK (
    (status = 'claimed' AND consumed_at IS NULL AND revoked_at IS NULL)
    OR (status = 'consumed' AND consumed_at IS NOT NULL AND revoked_at IS NULL)
    OR (status IN ('revoked', 'expired') AND revoked_at IS NOT NULL)
  ),
  CONSTRAINT ck_coupon_claims_time_order CHECK (
    (consumed_at IS NULL OR consumed_at >= claimed_at)
    AND (revoked_at IS NULL OR revoked_at >= claimed_at)
  )
);

CREATE INDEX idx_coupon_claims_customer_status
  ON public.coupon_claims (customer_id, status);

CREATE INDEX idx_coupon_claims_coupon_status
  ON public.coupon_claims (coupon_id, status);

DO $$
BEGIN
  IF EXISTS (
    SELECT 1
    FROM public.order_coupons
    WHERE coupon_id IS NULL
  ) THEN
    RAISE EXCEPTION
      'V738 guard: an order coupon has no source coupon for claim backfill';
  END IF;

  IF EXISTS (
    SELECT usage.coupon_id, orders.customer_id
    FROM public.order_coupons usage
    JOIN public.orders orders ON orders.id = usage.order_id
    WHERE usage.coupon_id IS NOT NULL
    GROUP BY usage.coupon_id, orders.customer_id
    HAVING count(*) > 1
  ) THEN
    RAISE EXCEPTION
      'V738 guard: one customer used the same coupon more than once';
  END IF;
END
$$;

INSERT INTO public.coupon_claims (
  coupon_id,
  customer_id,
  status,
  claimed_at,
  consumed_at
)
SELECT usage.coupon_id,
       orders.customer_id,
       CASE
         WHEN orders.payment_status = 'paid'::public.payment_status
          AND orders.status IN ('unshipped', 'shipped', 'completed')
           THEN 'consumed'::public.coupon_claim_status
         ELSE 'claimed'::public.coupon_claim_status
       END,
       usage.applied_at,
       CASE
         WHEN orders.payment_status = 'paid'::public.payment_status
          AND orders.status IN ('unshipped', 'shipped', 'completed')
           THEN COALESCE(orders.paid_at, usage.applied_at)
         ELSE NULL
       END
FROM public.order_coupons usage
JOIN public.orders orders ON orders.id = usage.order_id
WHERE usage.coupon_id IS NOT NULL;

ALTER TABLE public.order_coupons
  ADD COLUMN coupon_claim_id BIGINT;

UPDATE public.order_coupons usage
SET coupon_claim_id = claim.id
FROM public.orders orders,
     public.coupon_claims claim
WHERE orders.id = usage.order_id
  AND claim.coupon_id = usage.coupon_id
  AND claim.customer_id = orders.customer_id;

ALTER TABLE public.order_coupons
  ADD CONSTRAINT fk_order_coupons_coupon_claim_id
    FOREIGN KEY (coupon_claim_id) REFERENCES public.coupon_claims(id)
    ON UPDATE CASCADE ON DELETE RESTRICT;

CREATE UNIQUE INDEX uq_order_coupons_coupon_claim
  ON public.order_coupons (coupon_claim_id)
  WHERE coupon_claim_id IS NOT NULL;

DO $$
BEGIN
  IF EXISTS (
    SELECT 1
    FROM public.order_coupons
    WHERE coupon_claim_id IS NULL
  ) THEN
    RAISE EXCEPTION
      'V738 guard: an order coupon was not linked to a coupon claim';
  END IF;
END
$$;

ALTER TABLE public.order_coupons
  ALTER COLUMN coupon_claim_id SET NOT NULL;

UPDATE public.coupons coupon
SET claimed_quantity = counts.quantity,
    updated_at = now()
FROM (
  SELECT claim.coupon_id, count(*)::INTEGER AS quantity
  FROM public.coupon_claims claim
  WHERE claim.status IN ('claimed', 'consumed')
  GROUP BY claim.coupon_id
) counts
WHERE counts.coupon_id = coupon.id;

UPDATE public.coupons coupon
SET claimed_quantity = 0,
    updated_at = now()
WHERE NOT EXISTS (
  SELECT 1
  FROM public.coupon_claims claim
  WHERE claim.coupon_id = coupon.id
    AND claim.status IN ('claimed', 'consumed')
);

DO $$
BEGIN
  IF EXISTS (
    SELECT 1
    FROM public.coupons
    WHERE claimed_quantity > issue_quantity
  ) THEN
    RAISE EXCEPTION
      'V738 guard: existing claims exceed coupon issue_quantity';
  END IF;
END
$$;

CREATE FUNCTION public.allocate_coupon_claim_capacity()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
  IF NEW.status IN ('claimed', 'consumed') THEN
    UPDATE public.coupons
    SET claimed_quantity = claimed_quantity + 1,
        updated_at = now()
    WHERE id = NEW.coupon_id
      AND status = 'active'::public.coupon_status
      AND now() >= valid_from
      AND now() < valid_until
      AND claimed_quantity < issue_quantity;

    IF NOT FOUND THEN
      RAISE EXCEPTION
        'Coupon % is unavailable, expired, or fully claimed', NEW.coupon_id
        USING ERRCODE = 'check_violation';
    END IF;
  END IF;

  RETURN NEW;
END
$$;

CREATE FUNCTION public.sync_coupon_claim_capacity()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
DECLARE
  old_allocated BOOLEAN;
  new_allocated BOOLEAN;
BEGIN
  IF TG_OP = 'DELETE' THEN
    IF OLD.status IN ('claimed', 'consumed') THEN
      UPDATE public.coupons
      SET claimed_quantity = claimed_quantity - 1,
          updated_at = now()
      WHERE id = OLD.coupon_id
        AND claimed_quantity > 0;

      IF NOT FOUND THEN
        RAISE EXCEPTION
          'Coupon % claim counter cannot be released', OLD.coupon_id
          USING ERRCODE = 'check_violation';
      END IF;
    END IF;

    RETURN OLD;
  END IF;

  IF NEW.coupon_id <> OLD.coupon_id THEN
    RAISE EXCEPTION 'coupon_claims.coupon_id is immutable'
      USING ERRCODE = 'check_violation';
  END IF;

  old_allocated := OLD.status IN ('claimed', 'consumed');
  new_allocated := NEW.status IN ('claimed', 'consumed');

  IF old_allocated AND NOT new_allocated THEN
    UPDATE public.coupons
    SET claimed_quantity = claimed_quantity - 1,
        updated_at = now()
    WHERE id = OLD.coupon_id
      AND claimed_quantity > 0;

    IF NOT FOUND THEN
      RAISE EXCEPTION
        'Coupon % claim counter cannot be released', OLD.coupon_id
        USING ERRCODE = 'check_violation';
    END IF;
  ELSIF NOT old_allocated AND new_allocated THEN
    UPDATE public.coupons
    SET claimed_quantity = claimed_quantity + 1,
        updated_at = now()
    WHERE id = NEW.coupon_id
      AND status = 'active'::public.coupon_status
      AND now() >= valid_from
      AND now() < valid_until
      AND claimed_quantity < issue_quantity;

    IF NOT FOUND THEN
      RAISE EXCEPTION
        'Coupon % is unavailable, expired, or fully claimed', NEW.coupon_id
        USING ERRCODE = 'check_violation';
    END IF;
  END IF;

  RETURN NEW;
END
$$;

CREATE TRIGGER trg_coupon_claims_allocate_capacity
BEFORE INSERT ON public.coupon_claims
FOR EACH ROW
EXECUTE FUNCTION public.allocate_coupon_claim_capacity();

CREATE TRIGGER trg_coupon_claims_sync_capacity_on_update
BEFORE UPDATE ON public.coupon_claims
FOR EACH ROW
EXECUTE FUNCTION public.sync_coupon_claim_capacity();

CREATE TRIGGER trg_coupon_claims_sync_capacity_on_delete
BEFORE DELETE ON public.coupon_claims
FOR EACH ROW
EXECUTE FUNCTION public.sync_coupon_claim_capacity();

DROP VIEW public.coupon_usage_stats;

CREATE VIEW public.coupon_claim_stats AS
SELECT coupon.id AS coupon_id,
       coupon.issue_quantity,
       count(claim.id) FILTER (
         WHERE claim.status IN ('claimed', 'consumed')
       )::BIGINT AS claimed_quantity,
       count(claim.id) FILTER (
         WHERE claim.status = 'consumed'
       )::BIGINT AS consumed_quantity,
       (
         coupon.issue_quantity
         - count(claim.id) FILTER (
             WHERE claim.status IN ('claimed', 'consumed')
           )
       )::BIGINT AS remaining_claimable_quantity
FROM public.coupons coupon
LEFT JOIN public.coupon_claims claim ON claim.coupon_id = coupon.id
GROUP BY coupon.id, coupon.issue_quantity;

COMMENT ON VIEW public.coupon_claim_stats IS
  'Coupon issue capacity allocated at claim time; the 51st claim of a 50-quantity coupon must fail.';

COMMENT ON TABLE public.coupon_usage_adjustments IS
  'Legacy redemption adjustment ledger retained for audit; new capacity authority is coupon_claims.';
