-- Separate non-lifecycle events from order status history, then make the live
-- order header and status history share the same order_status enum.

CREATE TABLE public.order_event_history (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  source_history_id BIGINT NOT NULL,
  order_id VARCHAR(32) NOT NULL,
  event_type VARCHAR(24) NOT NULL,
  occurred_at TIMESTAMPTZ NOT NULL,
  actor_id VARCHAR(32),
  note TEXT,
  CONSTRAINT pk_order_event_history PRIMARY KEY (id),
  CONSTRAINT uq_order_event_history_source_history_id
    UNIQUE (source_history_id),
  CONSTRAINT fk_order_event_history_order_id
    FOREIGN KEY (order_id) REFERENCES public.orders(id)
    ON UPDATE CASCADE ON DELETE CASCADE,
  CONSTRAINT fk_order_event_history_actor_id
    FOREIGN KEY (actor_id) REFERENCES public.admin_users(id)
    ON UPDATE CASCADE ON DELETE RESTRICT,
  CONSTRAINT ck_order_event_history_type CHECK (btrim(event_type) <> '')
);

CREATE INDEX idx_order_event_history_order_time
  ON public.order_event_history (order_id, occurred_at);

CREATE INDEX idx_order_event_history_actor
  ON public.order_event_history (actor_id);

INSERT INTO public.order_event_history (
  source_history_id,
  order_id,
  event_type,
  occurred_at,
  actor_id,
  note
)
SELECT history.id,
       history.order_id,
       history.status,
       history.occurred_at,
       history.actor_id,
       history.note
FROM public.order_status_history history
WHERE history.status NOT IN (
  'unshipped',
  'shipped',
  'completed',
  'returned',
  'cancelled'
);

DELETE FROM public.order_status_history
WHERE status NOT IN (
  'unshipped',
  'shipped',
  'completed',
  'returned',
  'cancelled'
);

DO $$
BEGIN
  IF EXISTS (
    SELECT 1
    FROM public.orders
    WHERE status NOT IN (
      'unshipped',
      'shipped',
      'completed',
      'returned',
      'cancelled'
    )
  ) OR EXISTS (
    SELECT 1
    FROM public.order_status_history
    WHERE status NOT IN (
      'unshipped',
      'shipped',
      'completed',
      'returned',
      'cancelled'
    )
  ) THEN
    RAISE EXCEPTION
      'V740 guard: unsupported order lifecycle status remains';
  END IF;
END
$$;

CREATE TEMP TABLE v740_view_definitions (
  sort_order INTEGER PRIMARY KEY,
  view_name TEXT NOT NULL,
  view_definition TEXT NOT NULL,
  view_comment TEXT
) ON COMMIT DROP;

INSERT INTO v740_view_definitions (
  sort_order,
  view_name,
  view_definition,
  view_comment
)
SELECT source.sort_order,
       source.view_name,
       pg_get_viewdef(format('public.%I', source.view_name)::REGCLASS, true),
       obj_description(
         format('public.%I', source.view_name)::REGCLASS,
         'pg_class'
       )
FROM (VALUES
  (1, 'customer_spending_summary'),
  (2, 'customer_tier_summary')
) source(sort_order, view_name);

DROP VIEW public.customer_tier_summary;
DROP VIEW public.customer_spending_summary;

ALTER TABLE public.orders
  DROP CONSTRAINT ck_orders_status;

ALTER TABLE public.orders
  ALTER COLUMN status
  TYPE public.order_status
  USING status::public.order_status;

ALTER TABLE public.order_status_history
  ALTER COLUMN status
  TYPE public.order_status
  USING status::public.order_status;

DO $$
DECLARE
  saved_view RECORD;
BEGIN
  FOR saved_view IN
    SELECT view_name, view_definition, view_comment
    FROM v740_view_definitions
    ORDER BY sort_order
  LOOP
    EXECUTE format(
      'CREATE VIEW public.%I AS %s',
      saved_view.view_name,
      saved_view.view_definition
    );

    IF saved_view.view_comment IS NOT NULL THEN
      EXECUTE format(
        'COMMENT ON VIEW public.%I IS %L',
        saved_view.view_name,
        saved_view.view_comment
      );
    END IF;
  END LOOP;
END
$$;

COMMENT ON TABLE public.order_event_history IS
  'Non-lifecycle order events moved out of order_status_history before enum enforcement.';
